// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iejinloqvfxfmetihqkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllamlubG9xdmZ4Zm1ldGlocWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTg3MzYsImV4cCI6MjA2OTM3NDczNn0.1syrin5j85H-gSfuqZUhf_RR4ihpyG6JnGhk5Zewz10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});